FROM alpine:3
LABEL org.opencontainers.image.source="https://github.com/mulecode/tool-set"
LABEL org.opencontainers.image.description="This is a test image for Docker"

RUN apk update && apk upgrade

CMD ["echo", "Hello Loren"]
